### ISSUE TITLE
wasm env

### ISSUE THREAD

**Issue by tzemanovic** [anoma/anoma-archive#21]
depends on anoma/anoma#16 

Steps:

* Common wasm env (usable in both transaction codes and VPs):
  * [x] logging https://github.com/heliaxdev/anoma-prototype/issues/19
  * [x] storage read-only API https://github.com/heliaxdev/anoma-prototype/issues/20
  * [ ] math & crypto (needs some more design details)
    * [x] `ed25519` is being added in anoma/anoma#160
    * [ ] anoma/namada#4 
    * [x] anoma/anoma#225
    * [ ]  anoma/anoma#163 
  * [x] panics & aborts (also needs some more design details)
    * [x] for panics, we probably just want to add `[profile.release] panic = "abort"` to Cargo.toml, which tells to compiler to simply abort on panics
    * [x] ~~we can also add host functions `panic` for explicit panics from wasm~~ not needed, `panic!` macro works
* Transaction env:
  * [x] storage write access for all public state anoma/anoma#82 
  * [x] initialize a new account anoma/anoma#102 
* Validity predicate env:
  * [x] storage read access to account's sub-space for prior and posterior state (depends on anoma/anoma#82)
* [ ] wasm env injection anoma/anoma#79 
* [x] add eval-like function to VP wasm anoma/anoma#165

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762836493563) by [Unito](https://www.unito.io)
