### ISSUE TITLE
Tracking: build success on various platforms

### ISSUE THREAD

**Issue by juped** [anoma/anoma-archive#368]
* [x] Linux/glibc, x64
Builds and runs. Seems to work regardless of compiler (gcc/clang), may end up separating by compiler as well. Some dependency components need clang.
* [ ] Linux/musl, x64
Fails to build - dynamic linking failure in one of the dependencies. Seems to have to do with distribution builds rather than musl itself. Possibly alpine specific, needs more investigation.
* [ ] Linux/*, arm64
Not yet tested. I don't know whether to expect it to fail.
* [x] Mac/system libc, x64
Builds and runs. Just using system libs and the system clang. Might separate gcc/clang, but less relevant than Linux, and it still might not matter.
* [ ] Mac/ARM
The `wasmer-compiler-cranelift` doesn't work, but this is only used in the matchmaker.
* [ ] OpenBSD/system libc, x64
Hard blocked on wasmer; I don't know whether it actually needs porting work or is just arbitrarily excluded. Other minor build failures exist, are easily patchable.
* [ ] Your platform here
This list is not comprehensive.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763024930090) by [Unito](https://www.unito.io)

**Comment by tzemanovic** [comment]
related #474
